CREATE TABLE IF NOT EXISTS stt_daily_sync_runs (
    run_id CHAR(36) NOT NULL,
    schema_version VARCHAR(8) NOT NULL DEFAULT '1.1',
    idempotency_key VARCHAR(128) NOT NULL,
    scope VARCHAR(16) NOT NULL,
    target_trade_date DATE NOT NULL,
    source_policy VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    requested_codes JSON NOT NULL,
    ready_codes JSON NOT NULL,
    failed_codes JSON NOT NULL,
    coverage_ratio DECIMAL(7, 6) NOT NULL,
    upserted_rows INT NOT NULL DEFAULT 0,
    started_at DATETIME(6) NOT NULL,
    finished_at DATETIME(6) NOT NULL,
    evidence_refs JSON NOT NULL,
    failure_reasons JSON NOT NULL,
    PRIMARY KEY (run_id),
    UNIQUE KEY uk_daily_sync_idempotency (idempotency_key),
    INDEX idx_trading_date_scope (target_trade_date, scope),
    INDEX idx_status_finished_at (status, finished_at),
    INDEX idx_as_of_finished_at (finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短线交易日线同步审计';
