CREATE TABLE IF NOT EXISTS stt_evidence_snapshots (
    evidence_id CHAR(36) NOT NULL,
    schema_version VARCHAR(8) NOT NULL DEFAULT '1.1',
    code CHAR(6) NULL,
    kind VARCHAR(32) NOT NULL,
    as_of DATETIME(6) NOT NULL,
    source VARCHAR(64) NOT NULL,
    data_status VARCHAR(16) NOT NULL,
    payload_json JSON NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    raw_reference VARCHAR(512) NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    freshness_seconds INT NOT NULL,
    quality_flags_json JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (evidence_id),
    INDEX idx_code_kind_as_of (code, kind, as_of),
    INDEX idx_status_as_of (data_status, as_of),
    INDEX idx_as_of (as_of)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短线交易原始证据快照';

CREATE TABLE IF NOT EXISTS stt_capture_attempts (
    attempt_id CHAR(36) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    code CHAR(6) NULL,
    kind VARCHAR(32) NOT NULL,
    source VARCHAR(64) NOT NULL,
    started_at DATETIME(6) NOT NULL,
    finished_at DATETIME(6) NOT NULL,
    status VARCHAR(16) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    field_completeness DECIMAL(7, 6) NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    raw_reference VARCHAR(512) NULL,
    error_class VARCHAR(128) NULL,
    error_message TEXT NULL,
    PRIMARY KEY (attempt_id),
    UNIQUE KEY uk_capture_idempotency (idempotency_key),
    INDEX idx_code_started_at (code, started_at),
    INDEX idx_status_started_at (status, started_at),
    INDEX idx_as_of_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短线交易采集尝试审计';

CREATE TABLE IF NOT EXISTS stt_source_health (
    health_id CHAR(36) NOT NULL,
    source VARCHAR(64) NOT NULL,
    kind VARCHAR(32) NOT NULL,
    window_started_at DATETIME(6) NOT NULL,
    window_ended_at DATETIME(6) NOT NULL,
    attempt_count INT NOT NULL,
    success_count INT NOT NULL,
    success_ratio DECIMAL(7, 6) NOT NULL,
    field_completeness DECIMAL(7, 6) NOT NULL,
    identity_mismatch_count INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (health_id),
    UNIQUE KEY uk_source_health_window (source, kind, window_started_at, window_ended_at),
    INDEX idx_status_window_ended_at (status, window_ended_at),
    INDEX idx_as_of_window_ended_at (window_ended_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短线交易数据源健康度';
