# sidestore-infra lan dnsmasq
listen-address=192.168.1.13
bind-dynamic
no-resolv
server=223.5.5.5
server=114.114.114.114
# 让 iOS 放弃 iCloud Private Relay DNS，改用本机 DNS
local=/mask.icloud.com/
local=/mask-h2.icloud.com/
address=/ani.yoloworld.site/192.168.1.13
address=/config.yoloworld.site/192.168.1.13
address=/hub.yoloworld.site/192.168.1.13
log-queries
log-facility=/tmp/dnsmasq-sidestore.log
